@server = http://localhost:8080

### 연결확인
get {{server}}/member

### 모든리스트 조회
get {{server}}/member/list

### 회원가입 요청
POST {{server}}/member
Content-Type: application/json; charset=UTF-8

{
  "member_name": "카나다지",
  "member_password": "1234"
}

### 정보수정
patch {{server}}/member
Content-Type: application/json; charset=UTF-8

{
  "member_id" : "7",
  "member_password": "12354"
}

### 회원삭제
delete {{server}}/member/5

### 게시글 등록
POST {{server}}/board
Content-Type: application/json; charset=UTF-8

{
  "board_writer": "1",
  "board_title": "35555",
  "board_content" : "Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores consectetur itaque magni deserunt nesciunt ea, impedit veritatis laborum, qui tenetur illo quibusdam! Culpa, aperiam eum! Architecto eveniet minima rerum sequi."
}


### 게시글 전체 조회 요청 //세션정보가 없을땐 /index로 리다이렉트됨
GET {{server}}/board


### 게시글 상세 조회 요청
GET {{server}}/board/2

### 게시글 업데이트 요청
PATCH {{server}}/board
Content-Type: application/json; charset=UTF-8

{
  "board_id" : "1",
  "board_title" : "수정됨",
  "board_content" : "내용도 수정됨!"
}

### 게시글삭제
delete {{server}}/board/1

### 아이디 존재 체크

post {{server}}/member/check
Content-Type: application/json; charset=UTF-8

{
  "username" : "project134"
}
